analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.3799283
  brandStrength: 0.9478273610584438
  lightness: 0.6415771
  brandColors:
    - '#1F1C19'
    - '#3079A2'
    - '#FCF2DF'
    - '#918877'
    - '#6EB4D8'
  rhythmicContrast: 0.5985663
typography_spectrum: 0.4587814
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 1
favicon: null
name: bighorn
